export const ariaAttributes = [
  'aria-activedescendant',
  'aria-atomic',
  'aria-autocomplete',
  'aria-busy',
  'aria-checked',
  'aria-colcount',
  'aria-colindex',
  'aria-colspan',
  'aria-controls',
  'aria-current',
  'aria-describedby',
  'aria-details',
  'aria-disabled',
  'aria-dropeffect',
  'aria-errormessage',
  'aria-expanded',
  'aria-flowto',
  'aria-grabbed',
  'aria-haspopup',
  'aria-hidden',
  'aria-invalid',
  'aria-keyshortcuts',
  'aria-label',
  'aria-labelledby',
  'aria-level',
  'aria-live',
  'aria-modal',
  'aria-multiline',
  'aria-multiselectable',
  'aria-orientation',
  'aria-owns',
  'aria-placeholder',
  'aria-posinset',
  'aria-pressed',
  'aria-readonly',
  'aria-relevant',
  'aria-required',
  'aria-roledescription',
  'aria-rowcount',
  'aria-rowindex',
  'aria-rowspan',
  'aria-selected',
  'aria-setsize',
  'aria-sort',
  'aria-valuemax',
  'aria-valuemin',
  'aria-valuenow',
  'aria-valuetext',
]

export const booleanAttributes = ['disabled', 'checked', 'selected', 'required']

export const globalSvgAttributes = [
  'xml:base',
  'xml:lang',
  'xml:space',
  'alignment-baseline',
  'baseline-shift',
  'clip',
  'clip-path',
  'clip-rule',
  'color',
  'color-interpolation',
  'color-interpolation-filters',
  'color-profile',
  'color-rendering',
  'cursor',
  'direction',
  'display',
  'dominant-baseline',
  'fill',
  'fill-opacity',
  'fill-rule',
  'filter',
  'flood-color',
  'flood-opacity',
  'font-family',
  'font-size',
  'font-size-adjust',
  'font-stretch',
  'font-style',
  'font-variant',
  'font-weight',
  'glyph-orientation-horizontal',
  'glyph-orientation-vertical',
  'image-rendering',
  'letter-spacing',
  'lighting-color',
  'marker-end',
  'marker-mid',
  'marker-start',
  'mask',
  'opacity',
  'overflow',
  'pointer-events',
  'shape-rendering',
  'stop-color',
  'stop-opacity',
  'stroke',
  'stroke-dasharray',
  'stroke-dashoffset',
  'stroke-linecap',
  'stroke-linejoin',
  'stroke-miterlimit',
  'stroke-opacity',
  'stroke-width',
  'text-anchor',
  'text-decoration',
  'text-rendering',
  'unicode-bidi',
  'visibility',
  'word-spacing',
  'writing-mode',
]

export const specificSvgAttributes = {
  svg: ['width', 'height', 'viewBox', 'preserveAspectRatio', 'xmlns', 'xmlns:xlink'],
  circle: ['cx', 'cy', 'r'],
  ellipse: ['cx', 'cy', 'rx', 'ry'],
  line: ['x1', 'x2', 'y1', 'y2'],
  rect: ['x', 'y', 'width', 'height', 'rx', 'ry'],
  polygon: ['points'],
  polyline: ['points'],
  path: ['d', 'pathLength'],
  text: ['x', 'y', 'dx', 'dy', 'rotate', 'textLength', 'lengthAdjust'],
  tspan: ['x', 'y', 'dx', 'dy', 'rotate', 'textLength', 'lengthAdjust'],
  g: [],
  defs: [],
  use: ['xlink:href', 'x', 'y', 'width', 'height'],
  symbol: ['viewBox', 'preserveAspectRatio'],
  marker: ['markerHeight', 'markerUnits', 'markerWidth', 'orient', 'refX', 'refY'],
  pattern: ['patternContentUnits', 'patternTransform', 'patternUnits'],
  clipPath: ['clipPathUnits'],
  mask: ['maskContentUnits', 'maskUnits', 'x', 'y', 'width', 'height'],
  animate: [
    'attributeName',
    'from',
    'to',
    'by',
    'dur',
    'begin',
    'end',
    'repeatCount',
    'repeatDur',
    'keyTimes',
    'keySplines',
    'calcMode',
    'values',
  ],
  animateTransform: [
    'attributeName',
    'type',
    'from',
    'to',
    'by',
    'dur',
    'begin',
    'end',
    'repeatCount',
    'repeatDur',
    'keyTimes',
    'keySplines',
    'calcMode',
    'values',
  ],
  animateMotion: ['path', 'keyPoints', 'rotate', 'origin'],
  animateColor: [
    'attributeName',
    'from',
    'to',
    'by',
    'dur',
    'begin',
    'end',
    'repeatCount',
    'repeatDur',
    'keyTimes',
    'keySplines',
    'calcMode',
    'values',
  ],
  set: ['attributeName', 'to', 'begin', 'end', 'dur'],
  filter: ['x', 'y', 'width', 'height', 'filterUnits', 'primitiveUnits', 'xlink:href'],
  feGaussianBlur: ['in', 'stdDeviation'],
  feOffset: ['in', 'dx', 'dy'],
  feBlend: ['in', 'in2', 'mode'],
  feColorMatrix: ['in', 'type', 'values'],
  feComponentTransfer: ['in'],
  feComposite: ['in', 'in2', 'operator', 'k1', 'k2', 'k3', 'k4'],
  feConvolveMatrix: [
    'in',
    'order',
    'kernelMatrix',
    'divisor',
    'bias',
    'targetX',
    'targetY',
    'edgeMode',
    'kernelUnitLength',
    'preserveAlpha',
  ],
  feDiffuseLighting: ['in', 'surfaceScale', 'diffuseConstant', 'kernelUnitLength'],
  feDisplacementMap: ['in', 'in2', 'scale', 'xChannelSelector', 'yChannelSelector'],
  feDistantLight: ['azimuth', 'elevation'],
  feFlood: ['flood-color', 'flood-opacity'],
  feFuncA: ['type', 'tableValues', 'slope', 'intercept', 'amplitude', 'exponent', 'offset'],
  feFuncB: ['type', 'tableValues', 'slope', 'intercept', 'amplitude', 'exponent', 'offset'],
  feFuncG: ['type', 'tableValues', 'slope', 'intercept', 'amplitude', 'exponent', 'offset'],
  feFuncR: ['type', 'tableValues', 'slope', 'intercept', 'amplitude', 'exponent', 'offset'],
  feImage: ['xlink:href', 'preserveAspectRatio'],
  feMerge: [],
  feMergeNode: ['in'],
  feMorphology: ['in', 'operator', 'radius'],
  feSpecularLighting: ['in', 'surfaceScale', 'specularConstant', 'specularExponent', 'kernelUnitLength'],
  feTile: ['in'],
  feTurbulence: ['baseFrequency', 'numOctaves', 'seed', 'stitchTiles', 'type'],
}
