import antfu from '@antfu/eslint-config'
import nxPlugin from '@nx/eslint-plugin'

export default antfu(
  {
    // Core configuration
    type: 'lib',

    // Enable TypeScript with type-aware linting for high-signal rules
    typescript: {
      tsconfigPath: './tsconfig.base.json',
      // Exclude files from type-aware parsing that are not in tsconfig.
      // This allows linting these files for code quality rules while avoiding parsing errors.
      ignoresTypeAware: [
        // Test files in __tests__ folders are not included in tsconfig
        '**/__tests__/**',
        // Declaration files (.d.ts) are type definitions, not in tsconfig project
        '**/*.d.ts',
        // Markdown code blocks are extracted into virtual files (not part of tsconfig)
        '**/*.md/**',
        // directus-data-query is a non-NX data utility directory containing GraphQL codegen output.
        // The entry point files (index.ts, lib/gql/index.ts) are simple re-exports.
        // Exclude from type-aware parsing since they're not part of an NX project's tsconfig.
        'apps/directus-data-query/src/**',
        // Root tooling files (not part of any project tsconfig)
        'codegen.ts',
        'config/**/*.ts',
        'tools/**/*.ts',
        'tools/**/*.tsx',
      ],
    },

    // Enable React
    react: true,

    // Enable stylistic formatting (replaces prettier for code style)
    stylistic: {
      indent: 2,
      quotes: 'single',
      semi: false,
    },

    // Enable JSON linting with @antfu/eslint-config's jsonc support
    // This provides formatting and schema validation for JSON files
    jsonc: true,
    // YAML not used in this project
    yaml: false,

    // Ignore patterns
    ignores: [
      // Build artifacts and caches (auto-generated, never authored)
      '**/node_modules/**',
      '**/dist/**',
      '**/build/**',
      '**/.nx/**',
      '**/.next/**',
      '**/coverage/**',
      '**/.cache/**',
      '**/storybook-static/**',
      // TypeScript declaration files - only ignore truly generated/non-editable files
      // next-env.d.ts is auto-generated by Next.js (comment says "should not be edited")
      '**/next-env.d.ts',
      // .next types are generated by Next.js during development
      '**/.next/**/*.d.ts',
      // Generated code from GraphQL codegen tools
      // These paths match the output directories configured in:
      //   - codegen.ts (root) -> apps/directus-data-query/src/lib/gql/generated/
      //   - libs/directus/directus-block (uses similar pattern) -> libs/directus/directus-block/src/generated/
      //   - libs/directus/directus-query/codegen-admin.ts -> libs/directus/directus-query/src/lib/gql/admin/generated/
      'apps/directus-data-query/src/lib/gql/generated/**',
      'libs/directus/directus-block/src/generated/**',
      'libs/directus/directus-query/src/lib/gql/admin/generated/**',
      // Config files are linted with relaxed rules in the 'config-files' block below
      // Test files in __tests__ folders (core-lib, directus-node) are NOW linted.
      // They are covered by the 'test-files' config block which disables type-aware rules.
      // This allows linting for code quality (unused vars, console usage, etc.) while
      // avoiding type-aware rule parsing errors (files not in tsconfig project service).
      // See: test-files config block below for relaxed rules applied to __tests__/**
      // Jest config at library roots - uses require() and isn't in tsconfig
      'libs/**/jest.config.ts',
      // Vite config files use relative imports to shared config (config/external-deps.ts).
      // This is intentional - the shared config manages external dependencies for library builds
      // and doesn't warrant its own NX library. Build configs are infrastructure, not app code.
      'libs/**/vite.config.ts',
      'libs/**/vitest.config.ts',
      'apps/**/vitest.config.ts',
      // Ignore stray JS/JS.map build artifacts in source directories
      // These are generated by TypeScript compilation and should not be linted
      // (The .ts/.tsx source files are the canonical source, not generated .js output)
      'apps/**/src/**/*.js',
      'apps/**/src/**/*.js.map',
      'apps/**/app/**/*.js',
      'apps/**/app/**/*.js.map',
      'libs/**/src/**/*.js',
      'libs/**/src/**/*.js.map',
      // Ignore root-level build artifacts (e.g., vitest.config.js, proxy.js, vite.config.js, etc.)
      'apps/**/*.js',
      'apps/**/*.js.map',
      'libs/**/*.js',
      'libs/**/*.js.map',
    ],
  },

  // NX Plugin configuration
  {
    name: 'nx/setup',
    plugins: {
      '@nx': nxPlugin,
    },
  },

  // NX dependency-checks rule for publishable library package.json files
  // Validates that dependencies declared in each library's package.json match actual imports.
  // Catches: missing dependencies, obsolete dependencies, version mismatches.
  // Uses the project graph to collect dependencies based on the build target input.
  // See: https://nx.dev/nx-api/eslint-plugin/documents/dependency-checks
  {
    name: 'nx/dependency-checks',
    files: ['libs/**/package.json'],
    rules: {
      '@nx/dependency-checks': [
        'error',
        {
          // Build targets to analyze for dependencies (default is ['build'])
          buildTargets: ['build'],
          // Check for missing dependencies (imports not in package.json)
          checkMissingDependencies: true,
          // Check for obsolete dependencies (in package.json but not imported)
          checkObsoleteDependencies: true,
          // Check that version specifiers match installed versions
          checkVersionMismatches: true,
          // Ignore build tool dependencies - these are in root devDependencies
          // and imported by vite.config.ts which is analyzed as build input.
          // The rule incorrectly flags them as missing because vite.config.ts
          // is part of the build target's input files.
          ignoredDependencies: [
            // Build tool dependencies (in root devDependencies)
            // These are imported by vite.config.ts which is analyzed as build input
            '@nx/vite',
            '@nx/react',
            '@vitejs/plugin-react',
            '@vitejs/plugin-react-swc',
            'vite',
            'vite-plugin-dts',
            'rollup-plugin-preserve-directives',
            // Test infrastructure (in root devDependencies)
            'vitest',
          ],
          // Include transitive dependencies (dependencies of dependencies)
          includeTransitiveDependencies: false,
        },
      ],
    },
  },

  // NX enforce-module-boundaries rule for all TS/JS files
  // Enforces strict boundaries between projects to prevent unplanned cross-dependencies.
  // Uses allowCircularSelfDependency to allow libraries to import from their own package name
  // (e.g., import { Box } from '@okam/stack-ui' within stack-ui itself).
  {
    name: 'nx/module-boundaries',
    files: ['**/*.ts', '**/*.tsx', '**/*.js', '**/*.jsx'],
    rules: {
      '@nx/enforce-module-boundaries': [
        'error',
        {
          enforceBuildableLibDependency: true,
          allowCircularSelfDependency: true,
          // Allow demo app to import from directus-data-query app (generated GraphQL types)
          // and static assets from libs for demo purposes.
          // Also allow transitional path imports that should eventually use package names.
          allow: [
            '@demo/directus-data-query',
            'libs/stack/stack-ui/static/**',
            'apps/directus-data-query/src',
          ],
          depConstraints: [
            {
              sourceTag: '*',
              onlyDependOnLibsWithTags: ['*'],
            },
          ],
        },
      ],
    },
  },

  // TypeScript-specific overrides
  {
    name: 'typescript/overrides',
    files: ['**/*.ts', '**/*.tsx'],
    rules: {
      // ts/consistent-type-imports - using @antfu/eslint-config default: ['error', { prefer: 'type-imports' }]

      // DEVIATIONS FROM DEFAULTS (intentional):
      // ts/no-explicit-any: antfu default is 'off', we enable as error to enforce proper typing
      // Explicit any should be avoided; use unknown, generics, or specific types instead
      'ts/no-explicit-any': 'error',
      // ts/no-unused-vars: rely on unused-imports/no-unused-vars to avoid duplicate reports
      'ts/no-unused-vars': 'off',

      // Type-aware rules - enabled for high-signal linting
      // These catch real bugs: unhandled promises, any leakage, async misuse
      'ts/no-floating-promises': 'error',
      'ts/no-misused-promises': 'error',
      'ts/await-thenable': 'error',
      'ts/require-await': 'error',
      // ts/no-unsafe-* rules upgraded from 'warn' to 'error' (strict mode)
      // Legitimate exceptions are handled via file-level config blocks:
      //   - react-stately-node-props (Node.props is typed as `any` in react-stately)
      //   - graphql-cms-data-boundaries (JSON scalars typed as `any` in GraphQL)
      //   - react-hook-form-integration (watch/getValues return `any`)
      //   - storybook, test-files, config-files (relaxed by design)
      'ts/no-unsafe-argument': 'error',
      'ts/no-unsafe-assignment': 'error',
      'ts/no-unsafe-call': 'error',
      'ts/no-unsafe-member-access': 'error',
      'ts/no-unsafe-return': 'error',

      // Type export consistency - enforce 'export type' for type-only exports
      'ts/consistent-type-exports': 'error',
      // ts/explicit-function-return-type: intentionally OFF
      // Return types should remain inferred - explicit return types are not desired for this codebase.
      // TypeScript's type inference is sufficient; explicit types add maintenance burden without benefit.
      'ts/explicit-function-return-type': 'off',
      'ts/strict-boolean-expressions': ['error', {
        // Allow nullable strings in conditionals (very common: if (str) ...)
        allowString: true,
        // Allow nullable numbers in conditionals (common: if (count) ...)
        allowNumber: true,
        // Allow nullable booleans (common: if (flag) ...)
        allowNullableBoolean: true,
        // Catch always-true object conditions (objects are never falsy)
        allowNullableObject: false,
        // Disallow any in conditionals - catches type safety issues
        allowAny: false,
        // Allow nullish RHS in && and || expressions
        allowRuleToRunWithoutStrictNullChecksIKnowWhatIAmDoing: false,
      }],
      'ts/unbound-method': 'error',
      'ts/naming-convention': 'off',
      'ts/no-unnecessary-type-assertion': 'error',
      'ts/no-redundant-type-constituents': 'error',
      'ts/prefer-nullish-coalescing': 'error',

      // Allow ts-expect-error with description
      'ts/ban-ts-comment': [
        'error',
        {
          'ts-expect-error': 'allow-with-description',
          'minimumDescriptionLength': 10,
          'ts-ignore': true,
          'ts-nocheck': true,
          'ts-check': false,
        },
      ],
    },
  },

  // Prevent React namespace imports in publishable libraries
  // Rollup minifies `import * as React` to `import * as u`, causing Next.js 15 + React 19
  // webpack to fail resolving u.createContext. Named imports minify correctly.
  // See: PR #396 for migration details
  {
    name: 'react/no-namespace-import',
    files: ['libs/**/*.ts', 'libs/**/*.tsx', 'libs/**/*.js', 'libs/**/*.jsx'],
    rules: {
      'no-restricted-syntax': [
        'error',
        {
          selector: 'ImportDeclaration[source.value="react"] > ImportNamespaceSpecifier',
          message: 'Avoid namespace imports from "react". Use named imports: `import { useState, useRef } from "react"`. Namespace imports cause minification issues with React 19 + Next.js 15.',
        },
      ],
    },
  },

  // General rule overrides - intentional deviations from @antfu/eslint-config defaults
  // Includes .mjs/.cjs for scripts like tools/scripts/publish.mjs
  {
    name: 'general/overrides',
    files: ['**/*.ts', '**/*.tsx', '**/*.js', '**/*.jsx', '**/*.mjs', '**/*.cjs'],
    rules: {
      // DEVIATIONS FROM DEFAULTS (intentional):
      // node/prefer-global/*: antfu default is ['error', 'never'], we allow process/Buffer globals
      // Reason: process.env is standard Node.js practice; requiring explicit import adds noise
      'node/prefer-global/process': 'off',
      'node/prefer-global/buffer': 'off',

      // jsdoc/*: antfu default is 'warn' for these, we disable (not enforcing JSDoc)
      // Reason: Team decision - JSDoc comments are optional, TypeScript provides type safety
      'jsdoc/require-returns-description': 'off',
      'jsdoc/check-param-names': 'off',
      'jsdoc/require-param': 'off',

      // unused-imports/no-unused-vars: antfu default is 'error', we match with custom ignore patterns
      // Variables/args prefixed with _ are allowed (common convention for intentionally unused params)
      'unused-imports/no-unused-vars': ['error', { argsIgnorePattern: '^_', varsIgnorePattern: '^_', ignoreRestSiblings: true }],

      // Import ordering rules - use @antfu/eslint-config default (perfectionist/sort-imports)
      // Enforces consistent import order: type imports first, then alphabetical within groups.
      // Auto-fixable. Enabled 2026-01-20 per team decision (Option A in evaluation report).
      // See: reports/perfectionist-sort-imports-evaluation.md

      // no-console - matches @antfu/eslint-config default: ['error', { allow: ['warn', 'error'] }]
      // Not set here - using default

      // Require justification for all ESLint disable comments
      // This prevents accumulation of unexplained bypasses over time.
      // Format: // eslint-disable-next-line rule-name -- justification here
      'eslint-comments/require-description': ['error', { ignore: [] }],

      // Catch stale/unnecessary eslint-disable comments
      // This prevents disables from accumulating after the underlying issue is fixed.
      // CI guardrail: ensures every disable is actually suppressing an error.
      'eslint-comments/no-unused-disable': 'error',
    },
  },

  // React-specific overrides
  {
    name: 'react/overrides',
    files: ['**/*.tsx', '**/*.jsx'],
    rules: {
      // Allow Tailwind 'tw' and CSS-in-JS 'css' props (not default DOM attributes)
      'react-dom/no-unknown-property': ['error', { ignore: ['css', 'tw'] }],
      // react/jsx-key-before-spread - matches @antfu/eslint-config default: 'warn'
      // Not set here - using default
    },
  },

  // React type-aware rules - TSX files only (requires TypeScript parser)
  // Upgraded from default 'warn' to 'error' per strict ESLint policy
  {
    name: 'react/type-aware',
    files: ['**/*.tsx'],
    rules: {
      // Prevent leaked conditional rendering (e.g., {count && <X />} rendering "0")
      // This rule requires type information and only works with .tsx files
      'react/no-leaked-conditional-rendering': 'error',
    },
  },

  // Config files - relaxed rules and no type-aware linting
  // Config files are often not in tsconfig and have special patterns
  {
    name: 'config-files',
    files: [
      '**/*.config.ts',
      '**/*.config.js',
      '**/*.config.mjs',
      '**/*.config.cjs',
      '**/*.config.cts',
      '**/*.config.mts',
      '**/*.preset.ts',
      '**/*.preset.js',
      '**/*.preset.mjs',
      '**/*.preset.cjs',
      '**/*.preset.cts',
      '**/*.preset.mts',
      '**/vite.config.*',
      '**/vitest.config.*',
      '**/jest.config.*',
      '**/next.config.*',
      '**/tailwind.config.*',
    ],
    rules: {
      'no-console': 'off',
      'ts/no-require-imports': 'off',
      // Disable type-aware rules for config files (often not in tsconfig)
      'ts/no-floating-promises': 'off',
      'ts/no-misused-promises': 'off',
      'ts/await-thenable': 'off',
      'ts/require-await': 'off',
      'ts/no-unsafe-argument': 'off',
      'ts/no-unsafe-assignment': 'off',
      'ts/no-unsafe-call': 'off',
      'ts/no-unsafe-member-access': 'off',
      'ts/no-unsafe-return': 'off',
    },
  },

  // CommonJS files - relaxed TypeScript rules
  {
    name: 'commonjs',
    files: ['**/*.js', '**/*.cjs'],
    rules: {
      'ts/no-require-imports': 'off',
    },
  },

  // TypeScript declaration files (.d.ts) - relaxed rules for type definitions
  // Declaration files define types without runtime code, so many rules don't apply.
  // Now linting authored .d.ts files (schema.d.ts, tiptap.d.ts) instead of ignoring all.
  {
    name: 'declaration-files',
    files: ['**/*.d.ts'],
    rules: {
      // Declaration files often need explicit any for external module augmentation
      'ts/no-explicit-any': 'off',
      // Module augmentation often requires unused generic parameters to match external interfaces
      'ts/no-unused-vars': 'off',
      'unused-imports/no-unused-vars': 'off',
      // Type-aware rules are irrelevant for pure type declarations (no runtime code)
      'ts/no-floating-promises': 'off',
      'ts/no-misused-promises': 'off',
      'ts/await-thenable': 'off',
      'ts/require-await': 'off',
      'ts/no-unsafe-argument': 'off',
      'ts/no-unsafe-assignment': 'off',
      'ts/no-unsafe-call': 'off',
      'ts/no-unsafe-member-access': 'off',
      'ts/no-unsafe-return': 'off',
      'ts/strict-boolean-expressions': 'off',
      // ts/explicit-function-return-type: inherits global 'off' setting (no override needed)
      'ts/consistent-type-exports': 'off',
      'ts/no-unnecessary-type-assertion': 'off',
      'ts/no-redundant-type-constituents': 'off',
      'ts/prefer-nullish-coalescing': 'off',
      'ts/unbound-method': 'off',
      // Allow triple-slash references in .d.ts files (common pattern)
      'ts/triple-slash-reference': 'off',
    },
  },

  // Automation library - NX generator code without strictNullChecks
  // ts/prefer-nullish-coalescing and ts/strict-boolean-expressions require strictNullChecks
  {
    name: 'automation-lib',
    files: ['libs/automation/**/*.ts'],
    rules: {
      'ts/prefer-nullish-coalescing': 'off',
      'ts/strict-boolean-expressions': 'off',
    },
  },

  // Test files - relaxed rules and no type-aware linting
  // Test files (especially __tests__/**) often aren't in tsconfig and use looser typing patterns.
  // All type-aware rules must be disabled to avoid parsing errors for files not in the project.
  {
    name: 'test-files',
    files: [
      '**/*.test.ts',
      '**/*.test.tsx',
      '**/*.spec.ts',
      '**/*.spec.tsx',
      '**/__tests__/**',
    ],
    rules: {
      'ts/no-explicit-any': 'off',
      'no-console': 'off',
      // Disable ALL type-aware rules for test files (especially __tests__/** not in tsconfig)
      // Promise/async rules
      'ts/no-floating-promises': 'off',
      'ts/no-misused-promises': 'off',
      'ts/await-thenable': 'off',
      'ts/require-await': 'off',
      // Unsafe type rules
      'ts/no-unsafe-argument': 'off',
      'ts/no-unsafe-assignment': 'off',
      'ts/no-unsafe-call': 'off',
      'ts/no-unsafe-member-access': 'off',
      'ts/no-unsafe-return': 'off',
      // Method binding
      'ts/unbound-method': 'off',
      // Type export/expression rules (require type information)
      'ts/consistent-type-exports': 'off',
      // ts/explicit-function-return-type: inherits global 'off' setting (no override needed)
      'ts/strict-boolean-expressions': 'off',
      'ts/no-unnecessary-type-assertion': 'off',
      'ts/no-redundant-type-constituents': 'off',
      'ts/prefer-nullish-coalescing': 'off',
    },
  },

  // directus-data-query - non-NX data utility directory containing GraphQL codegen output
  // Entry point files (index.ts, lib/gql/index.ts) are simple re-exports not part of an NX project.
  // Generated files in /generated/ are already ignored in main ignores.
  // Disable type-aware rules since these files are not in an NX project's tsconfig.
  {
    name: 'directus-data-query',
    files: ['apps/directus-data-query/src/**/*.ts'],
    rules: {
      // Disable ALL type-aware rules (files not in NX project tsconfig)
      'ts/no-floating-promises': 'off',
      'ts/no-misused-promises': 'off',
      'ts/await-thenable': 'off',
      'ts/require-await': 'off',
      'ts/no-unsafe-argument': 'off',
      'ts/no-unsafe-assignment': 'off',
      'ts/no-unsafe-call': 'off',
      'ts/no-unsafe-member-access': 'off',
      'ts/no-unsafe-return': 'off',
      'ts/unbound-method': 'off',
      'ts/consistent-type-exports': 'off',
      'ts/strict-boolean-expressions': 'off',
      'ts/no-unnecessary-type-assertion': 'off',
      'ts/no-redundant-type-constituents': 'off',
      'ts/prefer-nullish-coalescing': 'off',
    },
  },

  // Storybook files - relaxed type-aware rules for story patterns
  {
    name: 'storybook',
    files: ['**/*.stories.ts', '**/*.stories.tsx', '**/*.stories.js', '**/*.stories.jsx', '**/.storybook/**/*.ts', '**/.storybook/**/*.js'],
    rules: {
      // Storybook uses default exports
      'import/no-default-export': 'off',
      // Allow console.log in stories for debugging
      'no-console': 'off',
      // Allow hooks in CSF3 render functions - Storybook treats render() as a component
      // See: https://storybook.js.org/docs/writing-stories#using-hooks-in-render-functions
      'react-hooks/rules-of-hooks': 'off',
      // Relax type-aware rules for stories (common patterns with any/unknown)
      'ts/no-unsafe-argument': 'off',
      'ts/no-unsafe-assignment': 'off',
      'ts/no-unsafe-call': 'off',
      'ts/no-unsafe-member-access': 'off',
      'ts/no-unsafe-return': 'off',
      'ts/no-misused-promises': 'off',
    },
  },

  // Next.js app directory files (pages, layouts, etc. use default exports)
  {
    name: 'nextjs',
    files: [
      '**/app/**/page.tsx',
      '**/app/**/layout.tsx',
      '**/app/**/loading.tsx',
      '**/app/**/error.tsx',
      '**/app/**/not-found.tsx',
      '**/app/**/template.tsx',
      '**/pages/**/*.tsx',
    ],
    rules: {
      'import/no-default-export': 'off',
    },
  },

  // Demo app - allow console.log for debugging
  {
    name: 'demo-app',
    files: ['apps/demo/**/*.ts', 'apps/demo/**/*.tsx'],
    rules: {
      'no-console': 'warn',
    },
  },

  // Provider files - allow exporting both Provider component and useContext hook
  // This is an intentional React Context pattern where Provider + hook are co-located
  {
    name: 'provider-files',
    files: [
      '**/providers/**/index.tsx',
      '**/providers/**/*.tsx',
    ],
    rules: {
      'react-refresh/only-export-components': 'off',
    },
  },

  // Theme files - allow exporting theme utilities alongside components
  {
    name: 'theme-files',
    files: ['**/theme/index.tsx'],
    rules: {
      'react-refresh/only-export-components': 'off',
    },
  },

  // Storybook mock/helper files - allow mixed exports
  {
    name: 'storybook-helpers',
    files: ['**/storybook/**/*.tsx', '**/storybook/**/*.ts'],
    rules: {
      'react-refresh/only-export-components': 'off',
    },
  },

  // React-stately collection Item components (AccordionItem, TabItem, TagItem, Option, Node)
  // These have getCollectionNode static methods that trigger the warning
  {
    name: 'react-stately-items',
    files: [
      '**/AccordionItem.tsx',
      '**/TabItem.tsx',
      '**/TagItem.tsx',
      '**/Option/index.tsx',
      '**/Node/index.tsx',
      '**/AlertsItem.tsx',
    ],
    rules: {
      'react-refresh/only-export-components': 'off',
    },
  },

  // React.Children and cloneElement usage in react-aria/react-stately compatible components
  // These patterns are REQUIRED for react-stately collections (Item, Section, Node types)
  // and for react-aria component composition (Popover trigger injection, alert close buttons).
  // See: https://react-spectrum.adobe.com/react-stately/collections.html
  // Adobe's own react-spectrum library uses identical patterns in Item.ts
  {
    name: 'react-stately-children-api',
    files: [
      // React-stately collection Item components use getCollectionNode which requires Children API
      '**/AccordionItem.tsx',
      '**/TabItem.tsx',
      '**/TagItem.tsx',
      '**/Option/index.tsx',
      '**/Node/index.tsx',
      // Accordion state management uses Children.toArray for react-stately integration
      '**/useAccordionState.ts',
      // Components using cloneElement for prop injection (react-aria pattern)
      '**/AlertsItem.tsx',
      '**/Popover/index.tsx',
      '**/Popover/components/Button.tsx',
    ],
    rules: {
      // Disable all React.Children API warnings - required for react-stately collections
      'react/no-children-count': 'off',
      'react/no-children-for-each': 'off',
      'react/no-children-map': 'off',
      'react/no-children-only': 'off',
      'react/no-children-to-array': 'off',
      // Disable cloneElement warning - required for react-aria component composition
      'react/no-clone-element': 'off',
    },
  },

  // React-aria/react-stately hooks return plain objects with arrow function properties.
  // TypeScript incorrectly flags destructured methods as unbound class methods.
  // See: https://github.com/adobe/react-spectrum (all hooks return arrow functions)
  // Example false positives:
  //   - const { contains } = useFilter() - contains is an arrow function
  //   - const { close } = state (from useOverlayTriggerState) - close is arrow function
  //   - const { setSelectedKey } = tabState (from context) - React state setter
  {
    name: 'react-aria-unbound-method',
    files: [
      // Components using react-aria hooks that return arrow functions
      '**/ComboBox/index.tsx',
      '**/CheckboxGroupItem/index.tsx',
      // Components using react-stately overlay state (state.close is arrow function)
      '**/Popover/index.tsx',
      '**/CalendarPopover.tsx',
      '**/Select/components/Popover.tsx',
      // Components using react-stately accordion state
      '**/useAccordionState.ts',
      // Components using context-based state setters
      '**/MenuItems.tsx',
      '**/storybook/Menu/Menu.tsx',
    ],
    rules: {
      // Disable unbound-method - react-aria/react-stately return arrow functions, not class methods
      'ts/unbound-method': 'off',
    },
  },

  // WysiwygBlock - allow dangerouslySetInnerHTML with sanitized content
  // This component uses sanitize-html to sanitize all user content before rendering.
  // The dangerouslySetInnerHTML is safe because content passes through sanitize-html
  // with strict allowedTags and allowedAttributes configuration.
  // See: libs/stack/stack-ui/src/components/WysiwygBlock/index.tsx
  // See: docs/ADR/004_eslint-disable-policy.md (approved exception)
  {
    name: 'wysiwyg-sanitized-html',
    files: ['**/WysiwygBlock/index.tsx'],
    rules: {
      'react-dom/no-dangerously-set-innerhtml': 'off',
    },
  },

  // React-stately Node<T> props access - Node interface has `props?: any` by design
  // This is an intentional design choice in @react-types/shared (v3.x) to allow arbitrary
  // props on collection items. See: node_modules/@react-types/shared/src/collections.d.ts:222
  // The `any` leaks into all components that access item.props from Node<T>.
  // Example: const { icon, title } = item.props - props is typed as `any` in react-stately
  // These warnings are unavoidable without upstream library changes.
  // Type safety is enforced through the component's generic type parameter (e.g., Node<TAccordionItemProps>)
  {
    name: 'react-stately-node-props',
    files: [
      // Components consuming react-stately Node<T>.props (typed as `any` in the library)
      '**/AriaAccordionItem.tsx',
      '**/Option/index.tsx',
      '**/ListBoxSection.tsx',
      '**/TabPanel.tsx',
      '**/TagItem.tsx',
      '**/TagGroup/index.tsx',
    ],
    rules: {
      // Disable ts/no-unsafe-* rules for react-stately Node.props access
      // The `any` type originates from the library's Node interface
      'ts/no-unsafe-argument': 'off',
      'ts/no-unsafe-assignment': 'off',
      'ts/no-unsafe-call': 'off',
      'ts/no-unsafe-member-access': 'off',
      'ts/no-unsafe-return': 'off',
      // Disable strict-boolean-expressions for props from Node.props (typed as `any`)
      // Example: {icon && <Icon />} where icon comes from item.props which is `any`
      'ts/strict-boolean-expressions': 'off',
    },
  },

  // GraphQL codegen output and CMS data boundaries
  // These files interact with GraphQL fragments that have JSON scalar types (any in TypeScript)
  // or CMS data where tokens/variants may be null/undefined from the database.
  // Type safety is enforced at the UI component boundary, not at the data fetching layer.
  {
    name: 'graphql-cms-data-boundaries',
    files: [
      // GraphQL fragment access where scalars are typed as `any`
      'libs/directus/directus-block/src/utils/getBlock.ts',
      'libs/directus/directus-block/src/utils/getBlockProps.ts',
      // CMS navigation items with nullable tokens
      'libs/directus/directus-next-component/src/utils/getNavigationItems/index.tsx',
      // TipTap rich text rendering with JSON content (attrs is Record<string, any>)
      'libs/directus/directus-flexible-content/src/lib/functions/renderView.ts',
      'libs/directus/directus-flexible-content/src/lib/functions/injectDataIntoContent.ts',
    ],
    rules: {
      // Relax ts/no-unsafe-* rules for CMS/GraphQL data boundaries
      'ts/no-unsafe-argument': 'off',
      'ts/no-unsafe-assignment': 'off',
      'ts/no-unsafe-call': 'off',
      'ts/no-unsafe-member-access': 'off',
      'ts/no-unsafe-return': 'off',
      // Relax strict-boolean-expressions for attrs from TipTap JSONContent (attrs is Record<string, any>)
      'ts/strict-boolean-expressions': 'off',
    },
  },

  // React-hook-form integration components
  // react-hook-form's watch() and getValues() return `any` by design because
  // form field values can be of any type depending on the field's configuration.
  // Type safety is enforced through the form schema, not the hook return types.
  {
    name: 'react-hook-form-integration',
    files: [
      // Form field components using react-hook-form Controller with watch/getValues
      '**/fields/ListBox/index.tsx',
      '**/fields/Select/Select.tsx',
      '**/fields/Checkbox/index.tsx',
      '**/fields/Radio/index.tsx',
      '**/fields/ComboBox/index.tsx',
    ],
    rules: {
      // Relax ts/no-unsafe-* rules for react-hook-form watch/getValues
      'ts/no-unsafe-assignment': 'off',
    },
  },

  // Theme provider hooks - theme tokens from context can be any JSON value
  {
    name: 'theme-provider-hooks',
    files: ['**/providers/Theme/hooks.ts'],
    rules: {
      'ts/no-unsafe-assignment': 'off',
      'ts/no-unsafe-return': 'off',
    },
  },
)
