packages:
  - 'apps/*'
  - 'libs/*'
  - 'libs/stack/*'
  - 'libs/directus/*'

overrides:
  dotenv: ^16.4.7
  axios: ">=1.13.5"
  immutable: ">=5.1.5"
  koa: ">=3.1.2"
  minimatch: ">=10.2.3"
  rollup: ">=4.59.0"
  serialize-javascript: ">=7.0.3"
  svgo: ">=3.3.3"
