// external deps that are not bundled when building and publishing libraries or apps

const externalDeps = [
  'react',
  'react-dom',
  'react/jsx-runtime',
  'react-aria',
  'react-stately',
  'isomorphic-dompurify',
  '@react-aria/calendar',
  '@react-aria/checkbox',
  '@react-aria/datepicker',
  '@react-aria/focus',
  '@react-aria/i18n',
  '@react-aria/overlays',
  '@react-aria/utils',
  '@react-aria/visually-hidden',
  '@react-stately/calendar',
  '@react-stately/datepicker',
  '@react-stately/overlays',
  '@react-stately/toggle',
  'react-i18next',
  'react-use',
  'react-spring',
  'react-div-100vh',
  'react-hook-form',
  'lodash',
  'radash',
  'lodash.isequal',
  'tailwind-variants',
  'unlazy',
  'next',
  'next/image',
  'graphql-request',
  '@tanstack/react-query',
  'dequal',
  'usehooks-ts',
]

export default externalDeps
