// external deps that are not bundled when building and publishing libraries or apps

const externalDeps = [
  'react',
  'react-dom',
  'react/jsx-runtime',
  'react-aria',
  'react-stately',
  'sanitize-html',
  "@react-aria/accordion",
  "@react-aria/focus",
  "@react-aria/i18n",
  "@react-spring/web",
  "@react-types/shared",
  "@tanstack/react-query",
  "@tiptap/core",
  "@tiptap/extension-blockquote",
  "@tiptap/extension-bold",
  "@tiptap/extension-bullet-list",
  "@tiptap/extension-code",
  "@tiptap/extension-code-block",
  "@tiptap/extension-document",
  "@tiptap/extension-hard-break",
  "@tiptap/extension-heading",
  "@tiptap/extension-horizontal-rule",
  "@tiptap/extension-italic",
  "@tiptap/extension-link",
  "@tiptap/extension-list-item",
  "@tiptap/extension-ordered-list",
  "@tiptap/extension-paragraph",
  "@tiptap/extension-strike",
  "@tiptap/extension-subscript",
  "@tiptap/extension-superscript",
  "@tiptap/extension-table",
  "@tiptap/extension-table-cell",
  "@tiptap/extension-table-header",
  "@tiptap/extension-table-row",
  "@tiptap/extension-text",
  "@tiptap/extension-text-align",
  "@tiptap/pm",
  "@tsed/exceptions",
  "dequal",
  "graphql",
  "graphql-request",
  "lodash.isequal",
  "next",
  "radashi",
  "react",
  "react-aria",
  "react-div-100vh",
  "react-dom",
  "react-hook-form",
  "react-stately",
  "react-use",
  "rollup-plugin-preserve-directives",
  "sanitize-html",
  "server-only",
  "swiper",
  "tailwind-variants",
  "tslib",
  "unlazy",
  "usehooks-ts"

]

export default externalDeps
