---
name: CI
on:
  push:
    branches:
      - main
      - release
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    container: node:18
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git config --system --add safe.directory '/__w/stack/stack'
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # - name: 📥 Monorepo install
      #  uses: ./.github/actions/yarn-nm-install

      - name: Use the package manager cache if available
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}
      - name: Install dependencies
        run: npm ci
        env:
          HUSKY: '0'  # By default do not run HUSKY install
          PRISMA_SKIP_POSTINSTALL_GENERATE: 'true'
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: '1'

      - name: NX Set SHA
        uses: nrwl/nx-set-shas@v3
      - name: Format Write
        run: npm run format-write
      - name: Build
        run: npm run build-ci
      - name: Publish Project to Chromatic
        uses: chromaui/action@v1
        # Chromatic GitHub Action options
        with:
          # 👇 Chromatic projectToken, refer to the manage page to obtain it.
          projectToken: ${{ secrets.CHROMATIC_TOKEN }}
          storybookBuildDir: dist/libs/stack/stack-ui
