name: CI
on:
  push:
    branches:
      - main
      - release
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    container: node:18
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git config --system --add safe.directory '/__w/stack-ui/stack-ui'
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: 📥 Monorepo install
        uses: ./.github/actions/yarn-nm-install

      - name: NX Set SHA
        uses: nrwl/nx-set-shas@v3
      - run: |
          yarn nx format:write
      - name: Build
        run: yarn nx run stack-ui:build-storybook --configuration=ci
      - name: Publish Project to Chromatic
        uses: chromaui/action@v1
        # Chromatic GitHub Action options
        with:
          # 👇 Chromatic projectToken, refer to the manage page to obtain it.
          projectToken: ${{ secrets.CHROMATIC_TOKEN }}
          storybookBuildDir: dist/storybook/stack-ui
