name: Publishing

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true
  workflow_run:
    workflows: [Semantic Release]
    types:
      - completed
permissions:
  contents: write
env:
  GITHUB_ACTOR: OKAMca

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@okam'

      - name: Configure Git
        shell: bash
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install dependencies
        shell: bash
        run: yarn install

      - name: Build Core Lib
        run: yarn build-core

      - name: Publish Core Lib Package
        run: yarn publish-core
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Build Stack UI
        run: yarn build-stack

      - name: Publish Stack UI Package
        run: yarn publish-stack
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
